### ISSUE TITLE
maven rep for draggable and droppable

### ISSUE THREAD

**Issue by biancashouse** [ArcBees/gwtquery-draggable-plugin#4]
Which mvn repo holds the 1.1.0-SNAPSHOT versions, please.
Or should I just download and install ?

**Comment by meriouma** [comment]
I don't think they are at the moment. We are in the process of moving and releasing those libraries for GWT 2.7. Please note that the groupId and artifactId will change. In the meantime I think the easiest way to get a snapshot is by checking out the master branch and manually do a mvn clean install

**Comment by biancashouse** [comment]
ok thanks.
i will wait for the new version.

On Wed, Jan 14, 2015 at 4:46 PM, Maxime Meriouma-Caron <
notifications@github.com> wrote:

> I don't think they are at the moment. We are in the process of moving and
> releasing those libraries for GWT 2.7. Please note that the groupId and
> artifactId will change
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ArcBees/gwtquery-draggable-plugin/issues/4#issuecomment-69872048
> .

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by meriouma** [comment]
You should now be able to use

```
<dependency>
    <groupId>com.arcbees.gquery</groupId>
    <artifactId>droppable</artifactId>
    <version>2.0-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.arcbees.gquery</groupId>
    <artifactId>draggable</artifactId>
    <version>2.0-SNAPSHOT</version>
</dependency>
```

Ensure you are using sonatype for snapshots :

```
<repositories>
        <repository>
            <id>sonatype.snapshots</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
</repositories>
```

**Comment by biancashouse** [comment]
Wow, that was quick.
I'll try it now.

The reason I was looking for a leter version of these 2 plugins is because
I found that the latest gquery 1.4.3-SNAPSHOT stops my touch drag from
working correctly. In the console I see the string RETTT being printed. I
have not looked deep into the code, but when I reverted to a previous
version of the 1.4.3-SNAPSHOT jar, the problem disappeared.

Anyway, I will let you know what happen after I update my pom for these 2
plugins.

Merci Bien,

Ian

On Wed, Jan 14, 2015 at 7:19 PM, Maxime Meriouma-Caron <
notifications@github.com> wrote:

> You should now be able to use
> 
> <dependency>
>     <groupId>com.arcbees.gquery</groupId>
>     <artifactId>droppable</artifactId>
>     <version>2.0-SNAPSHOT</version>
> </dependency>
> <dependency>
>     <groupId>com.arcbees.gquery</groupId>
>     <artifactId>draggable</artifactId>
>     <version>2.0-SNAPSHOT</version>
> </dependency>
> 
> Ensure you are using sonatype for snapshots :
> 
> <repositories>
>         <repository>
>             <id>sonatype.snapshots</id>
>             <name>Sonatype snapshot repository</name>
>             <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>         </repository>
> </repositories>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ArcBees/gwtquery-draggable-plugin/issues/4#issuecomment-69883085
> .

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
I notice that your new droppable pom refers to the old non-ArcBees
draggable 1.0.4, so there is a conflict:

```
<name>Droppable plugin for gQuery</name>

<artifactId>droppable</artifactId>

<packaging>jar</packaging>


<dependencies>

    <dependency>

        <groupId>junit</groupId>

        <artifactId>junit</artifactId>

    </dependency>

    <dependency>

        <groupId>com.google.gwt</groupId>

        <artifactId>gwt-user</artifactId>

    </dependency>

    <dependency>

        <groupId>com.google.gwt</groupId>

        <artifactId>gwt-dev</artifactId>

    </dependency>

    <dependency>

        <groupId>com.googlecode.gwtquery</groupId>

        <artifactId>gwtquery</artifactId>

    </dependency>

    <dependency>

        <groupId>com.googlecode.gwtquery.plugins</groupId>

        <artifactId>draggable-plugin</artifactId>

    </dependency>
</dependencies>
```

On Wed, Jan 14, 2015 at 9:30 PM, Ian White ian@biancashouse.com wrote:

> Wow, that was quick.
> I'll try it now.
> 
> The reason I was looking for a leter version of these 2 plugins is because
> I found that the latest gquery 1.4.3-SNAPSHOT stops my touch drag from
> working correctly. In the console I see the string RETTT being printed. I
> have not looked deep into the code, but when I reverted to a previous
> version of the 1.4.3-SNAPSHOT jar, the problem disappeared.
> 
> Anyway, I will let you know what happen after I update my pom for these 2
> plugins.
> 
> Merci Bien,
> 
> Ian
> 
> On Wed, Jan 14, 2015 at 7:19 PM, Maxime Meriouma-Caron <
> notifications@github.com> wrote:
> 
> > You should now be able to use
> > 
> > <dependency>
> >     <groupId>com.arcbees.gquery</groupId>
> >     <artifactId>droppable</artifactId>
> >     <version>2.0-SNAPSHOT</version>
> > </dependency>
> > <dependency>
> >     <groupId>com.arcbees.gquery</groupId>
> >     <artifactId>draggable</artifactId>
> >     <version>2.0-SNAPSHOT</version>
> > </dependency>
> > 
> > Ensure you are using sonatype for snapshots :
> > 
> > <repositories>
> >         <repository>
> >             <id>sonatype.snapshots</id>
> >             <name>Sonatype snapshot repository</name>
> >             <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
> >             <snapshots>
> >                 <enabled>true</enabled>
> >             </snapshots>
> >         </repository>
> > </repositories>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ArcBees/gwtquery-draggable-plugin/issues/4#issuecomment-69883085
> > .
> 
> ## 
> 
> Ian White
> h: +61 2 9948 9739
> m: +61 404 950 122
> skype (home): biancashouse

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
<dependency>

<groupId>com.arcbees.gquery</groupId>

<artifactId>droppable</artifactId>

<version>2.0-SNAPSHOT</version>

<exclusions>

<exclusion>

<groupId>com.googlecode.gwtquery.plugins</groupId>

<artifactId>draggable-plugin</artifactId>

</exclusion>

</exclusions>

</dependency>

<dependency>

  <groupId>com.arcbees.gquery</groupId>

 <artifactId>draggable</artifactId>

 <version>2.0-SNAPSHOT</version>

 </dependency>

On Wed, Jan 14, 2015 at 9:45 PM, Ian White ian@biancashouse.com wrote:

> I notice that your new droppable pom refers to the old non-ArcBees
> draggable 1.0.4, so there is a conflict:
> 
> ```
> <name>Droppable plugin for gQuery</name>
> 
> <artifactId>droppable</artifactId>
> 
> <packaging>jar</packaging>
> 
> 
> <dependencies>
> 
>     <dependency>
> 
>         <groupId>junit</groupId>
> 
>         <artifactId>junit</artifactId>
> 
>     </dependency>
> 
>     <dependency>
> 
>         <groupId>com.google.gwt</groupId>
> 
>         <artifactId>gwt-user</artifactId>
> 
>     </dependency>
> 
>     <dependency>
> 
>         <groupId>com.google.gwt</groupId>
> 
>         <artifactId>gwt-dev</artifactId>
> 
>     </dependency>
> 
>     <dependency>
> 
>         <groupId>com.googlecode.gwtquery</groupId>
> 
>         <artifactId>gwtquery</artifactId>
> 
>     </dependency>
> 
>     <dependency>
> 
>         <groupId>com.googlecode.gwtquery.plugins</groupId>
> 
>         <artifactId>draggable-plugin</artifactId>
> 
>     </dependency>
> </dependencies>
> ```
> 
> On Wed, Jan 14, 2015 at 9:30 PM, Ian White ian@biancashouse.com wrote:
> 
> > Wow, that was quick.
> > I'll try it now.
> > 
> > The reason I was looking for a leter version of these 2 plugins is
> > because I found that the latest gquery 1.4.3-SNAPSHOT stops my touch drag
> > from working correctly. In the console I see the string RETTT being
> > printed. I have not looked deep into the code, but when I reverted to a
> > previous version of the 1.4.3-SNAPSHOT jar, the problem disappeared.
> > 
> > Anyway, I will let you know what happen after I update my pom for these 2
> > plugins.
> > 
> > Merci Bien,
> > 
> > Ian
> > 
> > On Wed, Jan 14, 2015 at 7:19 PM, Maxime Meriouma-Caron <
> > notifications@github.com> wrote:
> > 
> > > You should now be able to use
> > > 
> > > <dependency>
> > >     <groupId>com.arcbees.gquery</groupId>
> > >     <artifactId>droppable</artifactId>
> > >     <version>2.0-SNAPSHOT</version>
> > > </dependency>
> > > <dependency>
> > >     <groupId>com.arcbees.gquery</groupId>
> > >     <artifactId>draggable</artifactId>
> > >     <version>2.0-SNAPSHOT</version>
> > > </dependency>
> > > 
> > > Ensure you are using sonatype for snapshots :
> > > 
> > > <repositories>
> > >         <repository>
> > >             <id>sonatype.snapshots</id>
> > >             <name>Sonatype snapshot repository</name>
> > >             <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
> > >             <snapshots>
> > >                 <enabled>true</enabled>
> > >             </snapshots>
> > >         </repository>
> > > </repositories>
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ArcBees/gwtquery-draggable-plugin/issues/4#issuecomment-69883085
> > > .
> > 
> > ## 
> > 
> > Ian White
> > h: +61 2 9948 9739
> > m: +61 404 950 122
> > skype (home): biancashouse
> 
> ## 
> 
> Ian White
> h: +61 2 9948 9739
> m: +61 404 950 122
> skype (home): biancashouse

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by jDramaix** [comment]
@meriouma could you fix that ?
