### ISSUE TITLE
Droppable 2.0-SNAPSHOT plugin won't compile

### ISSUE THREAD

**Issue by biancashouse** [ArcBees/gwtquery-draggable-plugin#6]
I now get many gwt compilation errors. Here's a simple example:

DragAndDropManager.getCurrentDraggable() does not exists...

public class DroppableHandler {

  private static enum PositionStatus {
    IS_OUT, IS_OVER;
  }

  public static DroppableHandler getInstance(Element droppable) {
    return $(droppable).data(DROPPABLE_HANDLER_KEY, DroppableHandler.class);
  }

  private Dimension droppableDimension;
  private Offset droppableOffset;
  private HasHandlers eventBus;
  private boolean greedyChild = false;
  private boolean isOut = true;
  private boolean isOver = false;
  private DroppableOptions options;

  private boolean visible = false;

  public DroppableHandler(DroppableOptions options, HasHandlers eventBus) {
    this.options = options;
    this.eventBus = eventBus;

  }

  public void activate(Element droppable, GqEvent e) {
    if (options.getActiveClass() != null) {
      droppable.addClassName(options.getActiveClass());
    }
    Element draggable = **DragAndDropManager.getInstance().getCurrentDraggable();**
    if (draggable != null) {
      if (options.getDraggableHoverClass() != null) {
        $(draggable).data(options.getDraggableHoverClass(), new Integer(0));
      }

**Comment by biancashouse** [comment]
ALSO - fyi - DragAndDropManagerImpl DOES implement getCurrentDraggable()

**Comment by meriouma** [comment]
What are the compile errors? They are gwt compile errors right? not java?

**Comment by biancashouse** [comment]
[INFO]    [ERROR] Errors in
'com/bh/gwt/module/client/common/tabs/visitor/signedin/SignedInVisitorViewImpl.java'

[INFO]       [ERROR] Line 148: Failed to resolve
'com.bh.gwt.module.client.common.tabs.visitor.signedin.SignedInVisitorViewImpl.HomeViewImplUiBinder'
via deferred binding

[INFO]    Tracing compile failure path for type
'gwtquery.plugins.droppable.client.DroppableHandler'

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/DroppableHandler.java'

[INFO]          [ERROR] Line 82: The method getCurrentDraggable() is
undefined for the type DragAndDropManager

[INFO]          [ERROR] Line 349: The method getAbsPosition() is undefined
for the type DraggableHandler

[INFO]          [ERROR] Line 100: The method getCurrentDraggable() is
undefined for the type DragAndDropManager

[INFO]          [ERROR] Line 352: The method getAbsPosition() is undefined
for the type DraggableHandler

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/DroppableOptions.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.DragAndDropContext cannot be
resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/DragAndDropContext.java'

[INFO]          [ERROR] Line 37: The constructor DragContext(Element) is
undefined

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/AbstractDroppableEvent.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.DragAndDropContext cannot be
resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/gwt/DroppableWidget.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.OutDroppableEvent.OutDroppableEventHandler
cannot be resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasAllDropHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.HasOverDroppableHandler cannot be
resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasOverDroppableHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.OverDroppableEvent.OverDroppableEventHandler
cannot be resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasDeactivateDroppableHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.DeactivateDroppableEvent.DeactivateDroppableEventHandler
cannot be resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasOutDroppableHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.OutDroppableEvent.OutDroppableEventHandler
cannot be resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasActivateDroppableHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.ActivateDroppableEvent.ActivateDroppableEventHandler
cannot be resolved to a type

[INFO]       [ERROR] Errors in
'gwtquery/plugins/droppable/client/events/HasDropHandler.java'

[INFO]          [ERROR]
gwtquery.plugins.droppable.client.events.DropEvent.DropEventHandler cannot
be resolved to a type

[INFO]    Tracing compile failure path for type
'gwtquery.plugins.droppable.client.DragAndDropManagerImpl'

[INFO

On Thu, Jan 15, 2015 at 9:34 AM, Maxime Meriouma-Caron <
notifications@github.com> wrote:

> What are the compile errors?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ArcBees/gwtquery-draggable-plugin/issues/6#issuecomment-70006253
> .

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
If you don't make the exclusion, you get these warnings, but compilation succeeds:

 --- gwt-maven-plugin:2.7.0-rc1:compile (gwt) @ gwt-module ---
     [exec] [INFO] Compiling module com.bh.gwt.module.GWT_Module
     [exec] [INFO]    Ignored 6 units with compilation errors in first pass.
     [exec] [INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
     [exec] [INFO]    Computing all possible rebind results for 'gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl'
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]       Rebinding gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl
     [exec] [INFO]          Could not find an exact match rule. Using 'closest' rule <replace-with class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/> based on fall back values. You may need to implement a specific binding in case the fall back behavior does not replace the missing binding
     [exec] [INFO]    Compiling 18 permutations

**Comment by meriouma** [comment]
Do you still have this problem? I've compiled master successfully

**Comment by biancashouse** [comment]
Hi Maxime,

Apologies for the late reply. We just had our Australia Day weekend. No
work, just beer.

When I get a chance, I will change my pom to your new snapshot again and
see what happens... and let you know...

Thanks

Ian

On Sun, Jan 25, 2015 at 2:11 PM, Maxime Meriouma-Caron <
notifications@github.com> wrote:

> Do you still have this problem? I've compiled master successfully
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ArcBees/gwtquery-draggable-plugin/issues/6#issuecomment-71348894
> .

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
Hi Max,

No change there. Your droppable plugin's pom has a dependency on draggable
1.0.4, so when I put both in my pom, the result looks like the same code as
I am using when i simply depend on enhance-plugin 1.0.5.

See attached.

Ian

On Tue, Jan 27, 2015 at 9:44 AM, Ian White ian@biancashouse.com wrote:

> Hi Maxime,
> 
> Apologies for the late reply. We just had our Australia Day weekend. No
> work, just beer.
> 
> When I get a chance, I will change my pom to your new snapshot again and
> see what happens... and let you know...
> 
> Thanks
> 
> Ian
> 
> On Sun, Jan 25, 2015 at 2:11 PM, Maxime Meriouma-Caron <
> notifications@github.com> wrote:
> 
> > Do you still have this problem? I've compiled master successfully
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ArcBees/gwtquery-draggable-plugin/issues/6#issuecomment-71348894
> > .
> 
> ## 
> 
> Ian White
> h: +61 2 9948 9739
> m: +61 404 950 122
> skype (home): biancashouse

## 

Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by meriouma** [comment]
I believe this is fixed, can you confirm?

**Comment by biancashouse** [comment]
I confirm that draggable and droppable 2.0-snapshot compile o.k. with
gquery 1.4.4-snapshot

Many thanks

Ian
BTW - mutation observer also working with them o.k. (so far)
