### ISSUE TITLE
I met a problem when I built a gwt project

### ISSUE THREAD

**Issue by lokisama** [ArcBees/gwtquery-draggable-plugin#7]
Excuse me , Would u like to write a  build.gradle config for ppl who like using gradle?

**Comment by olafleur** [comment]
Is this related to : https://github.com/ArcBees/gwtquery-droppable-plugin/issues/13#event-369567711 or is it a different problem?

**Comment by olafleur** [comment]
I'm not a Gradle expert, but from what I understand of it, you can add Maven Central to the dependencies of your project (in your build.gradle) and then add this project as a dependency to your project.

**Comment by lokisama** [comment]
Yes, you are right. Thank you for your help. Here is a part of my gradle dependencies.

repositories {
    mavenCentral()
    maven { url "http://repo.spring.io/libs-snapshot" }
    maven { url "http://oss.sonatype.org/content/repositories/snapshots" }
}

def gwtVersion = '2.7.0'
def gwtBootstrap3Version = '1.0-SNAPSHOT'
def gwtquery = '1.4.2'
def gqueryDraggable = '2.0-SNAPSHOT'
def gqueryDroppable = '2.0-SNAPSHOT'

dependencies {
  //gwt-query plugins by 3rd
  providedCompile "com.googlecode.gwtquery:gwtquery:${gwtquery}"
  providedCompile "com.arcbees.gquery:draggable:${gqueryDraggable}"
  providedCompile "com.arcbees.gquery:droppable:${gqueryDroppable}"

  //gwt
  providedCompile "com.google.gwt:gwt-user:${gwtVersion}"
  providedCompile "com.google.gwt:gwt-dev:${gwtVersion}"
  providedRuntime "com.google.gwt:gwt-servlet:${gwtVersion}"

  //gwtbootsrap3  0.9.1
  providedCompile "org.gwtbootstrap3:gwtbootstrap3:${gwtBootstrap3Version}"
  providedCompile "org.gwtbootstrap3:gwtbootstrap3-extras:${gwtBootstrap3Version}"

  //gwt-jackson
  providedCompile "com.github.nmorel.gwtjackson:gwt-jackson:0.7.0"
}

**Comment by olafleur** [comment]
Closing as, from what I understand, there is nothing more to be done.
